group = core
admin-port = 13000
admin-password = play
status-password = show
log-file = "/var/log/kannel/bearerbox.log"
log-level = 0
box-allow-ip = "127.0.0.1" # This opens the internal link for the wapbox daemon
wapbox-port = 13002 # This binds UDP ports 9200-9208 on all interfaces for mobile devices
wdp-interface-name = "*"

group = wapbox
bearerbox-host = 127.0.0.1
log-file = "/var/log/kannel/wapbox.log"
log-level = 0
syslog-level = none
map-url-max = 2
map-url-0 = "http://* http://bytey/HTML2WML?url=http://*"
map-url-1 = "https://* http://bytey/HTML2WML?url=https://*"
